### ISSUE TITLE
Signing fails: com.android.adservices.api.x509.pem (No such file or directory)

### ISSUE THREAD

**Issue by CyberShadow** [nix-community/robotnix#225]
Getting a bit further from #224, looks like the build succeeds, but the signing script fails:

```
Signing target files
2024-03-10 07:54:48 - common.py - WARNING : Failed to read SYSTEM/etc/build.prop
2024-03-10 07:54:48 - common.py - WARNING : Failed to read VENDOR/etc/build.prop
2024-03-10 07:54:48 - common.py - WARNING : Failed to read VENDOR_DLKM/etc/build.prop
2024-03-10 07:54:48 - common.py - WARNING : Failed to read VENDOR_DLKM/build.prop
2024-03-10 07:54:48 - common.py - WARNING : Failed to read build.prop for partition vendor_dlkm
2024-03-10 07:54:48 - common.py - WARNING : Failed to read ODM_DLKM/etc/build.prop
2024-03-10 07:54:48 - common.py - WARNING : Failed to read ODM_DLKM/build.prop
2024-03-10 07:54:48 - common.py - WARNING : Failed to read build.prop for partition odm_dlkm
2024-03-10 07:54:48 - common.py - WARNING : Failed to read SYSTEM_DLKM/etc/build.prop
2024-03-10 07:54:48 - common.py - WARNING : Failed to read SYSTEM_DLKM/build.prop
2024-03-10 07:54:48 - common.py - WARNING : Failed to read build.prop for partition system_dlkm
2024-03-10 07:54:48 - common.py - WARNING : Failed to read IMAGES/init_boot.img
Rewriting BOOT/RAMDISK/system/etc/ramdisk/build.prop:
  replace:  ro.bootimage.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/test-keys
     with:  ro.bootimage.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/release-keys
  replace:  ro.bootimage.build.tags=test-keys
     with:  ro.bootimage.build.tags=release-keys
Rewriting ODM/etc/build.prop:
  replace:  ro.odm.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/test-keys
     with:  ro.odm.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/release-keys
  replace:  ro.odm.build.tags=test-keys
     with:  ro.odm.build.tags=release-keys
    signing: OPlusFrameworksResCommon.apk                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: OPlusFrameworksResTarget.apk                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: OPlusSettingsProviderResTarget.apk                         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: OPlusSettingsResCommon.apk                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: OPlusSystemUIResCommon.apk                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: OPlusSystemUIResTarget.apk                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: Aperture.apk                                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: ApertureLensLauncher.apk                                   (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: Backgrounds.apk                                            (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: DeskClock.apk                                              (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: Etar.apk                                                   (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: ExactCalculator.apk                                        (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: Gallery2.apk                                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: Jelly.apk                                                  (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: LatinIME.apk                                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/shared)
    signing: LocalContactsBackup.apk                                    (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: ModuleMetadata.apk                                         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: PhotoTable.apk                                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: PowerOffAlarm.apk                                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/platform)
    signing: Recorder.apk                                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: RobotnixF-Droid.apk                                        (/dev/shm/robotnix_keys.XXXXlbhBzA/f-droid)
    signing: Robotnixchromium.apk                                       (/dev/shm/robotnix_keys.XXXXlbhBzA/chromium)
    signing: RobotnixchromiumTrichromeLibrary.apk                       (/dev/shm/robotnix_keys.XXXXlbhBzA/chromium)
    signing: Robotnixchromiumwebview.apk                                (/dev/shm/robotnix_keys.XXXXlbhBzA/chromiumwebview)
    signing: ThemesStub.apk                                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: messaging.apk                                              (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
Rewriting PRODUCT/etc/build.prop:
  replace:  ro.product.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/test-keys
     with:  ro.product.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/release-keys
  replace:  ro.product.build.tags=test-keys
     with:  ro.product.build.tags=release-keys
Rewriting PRODUCT/etc/selinux/product_mac_permissions.xml with new keys.
    signing: CarrierConfigResCommon.apk                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: DisplayCutoutEmulationCornerOverlay.apk                    (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: DisplayCutoutEmulationDoubleOverlay.apk                    (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: DisplayCutoutEmulationHoleOverlay.apk                      (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: DisplayCutoutEmulationTallOverlay.apk                      (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: DisplayCutoutEmulationWaterfallOverlay.apk                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: DocumentsUIOverlay.apk                                     (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: EmergencyInfo__auto_generated_rro_product.apk              (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: FontLatoOverlay.apk                                        (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: FontNotoSerifSourceOverlay.apk                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: FontRubikOverlay.apk                                       (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: FrameworksResCommon.apk                                    (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackCircularAndroidOverlay.apk                         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackCircularLauncherOverlay.apk                        (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackCircularSettingsOverlay.apk                        (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackCircularSystemUIOverlay.apk                        (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackFilledAndroidOverlay.apk                           (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackFilledLauncherOverlay.apk                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackFilledSettingsOverlay.apk                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackFilledSystemUIOverlay.apk                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackKaiAndroidOverlay.apk                              (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackKaiLauncherOverlay.apk                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackKaiSettingsOverlay.apk                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackKaiSystemUIOverlay.apk                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackRoundedAndroidOverlay.apk                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackRoundedLauncherOverlay.apk                         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackRoundedSettingsOverlay.apk                         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackRoundedSystemUIOverlay.apk                         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackSamAndroidOverlay.apk                              (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackSamLauncherOverlay.apk                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackSamSettingsOverlay.apk                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackSamSystemUIOverlay.apk                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackVictorAndroidOverlay.apk                           (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackVictorLauncherOverlay.apk                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackVictorSettingsOverlay.apk                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconPackVictorSystemUIOverlay.apk                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconShapePebbleOverlay.apk                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconShapeRoundedRectOverlay.apk                            (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconShapeSquareOverlay.apk                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconShapeSquircleOverlay.apk                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconShapeTaperedRectOverlay.apk                            (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconShapeTeardropOverlay.apk                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: IconShapeVesselOverlay.apk                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: ImsServiceEntitlement__auto_generated_rro_product.apk      (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: KeyHandler__auto_generated_rro_product.apk                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: LatinIME__auto_generated_rro_product.apk                   (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: LineageBlackTheme.apk                                      (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: LineageNavigationBarNoHint.apk                             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/platform)
    signing: LineageParts__auto_generated_rro_product.apk               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: LineageSettingsProvider__auto_generated_rro_product.apk    (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: LineageSetupWizard__auto_generated_rro_product.apk         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: ManagedProvisioning__auto_generated_rro_product.apk        (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: NavigationBarMode2ButtonOverlay.apk                        (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: NavigationBarMode3ButtonOverlay.apk                        (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: NavigationBarModeGesturalOverlay.apk                       (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: NavigationBarModeGesturalOverlayExtraWideBack.apk          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: NavigationBarModeGesturalOverlayNarrowBack.apk             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: NavigationBarModeGesturalOverlayWideBack.apk               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: NetworkStackOverlay.apk                                    (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: OplusDoze__auto_generated_rro_product.apk                  (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: SettingsProvider__auto_generated_rro_product.apk           (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: Settings__auto_generated_rro_product.apk                   (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: SimpleDeviceConfig__auto_generated_rro_product.apk         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: StorageManager__auto_generated_rro_product.apk             (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: SystemUIResCommon.apk                                      (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: SystemUI__auto_generated_rro_product.apk                   (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: TelephonyResCommon.apk                                     (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: TrebuchetOverlay.apk                                       (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: TrebuchetQuickStep__auto_generated_rro_product.apk         (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: Updater__auto_generated_rro_product.apk                    (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: WifiResCommon.apk                                          (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: framework-res__auto_generated_rro_product.apk              (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: org.lineageos.platform-res__auto_generated_rro_product.apk (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: Contacts.apk                                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/shared)
    signing: Dialer.apk                                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/shared)
    signing: Eleven.apk                                                 (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: HotwordEnrollmentOKGoogle.apk                              (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/platform)
    signing: HotwordEnrollmentXGoogle.apk                               (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/platform)
    signing: ImsServiceEntitlement.apk                                  (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: OneTimeInitializer.apk                                     (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
    signing: SettingsIntelligence.apk                                   (/dev/shm/robotnix_keys.XXXXlbhBzA/instantnoodlep/releasekey)
Rewriting RECOVERY/RAMDISK/default.prop:
Rewriting RECOVERY/RAMDISK/prop.default:
  replace:  ro.system.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/test-keys
     with:  ro.system.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/release-keys
  replace:  ro.system.build.tags=test-keys
     with:  ro.system.build.tags=release-keys
  replace:  ro.build.display.id=lineage_instantnoodlep-userdebug 13 TQ3A.230901.001 2023100409 test-keys
     with:  ro.build.display.id=lineage_instantnoodlep-userdebug 13 TQ3A.230901.001 2023100409
  replace:  ro.build.tags=test-keys
     with:  ro.build.tags=release-keys
  replace:  ro.vendor.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/test-keys
     with:  ro.vendor.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/release-keys
  replace:  ro.vendor.build.tags=test-keys
     with:  ro.vendor.build.tags=release-keys
  replace:  ro.odm.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/test-keys
     with:  ro.odm.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/release-keys
  replace:  ro.odm.build.tags=test-keys
     with:  ro.odm.build.tags=release-keys
  replace:  ro.product.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/test-keys
     with:  ro.product.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/release-keys
  replace:  ro.product.build.tags=test-keys
     with:  ro.product.build.tags=release-keys
  replace:  ro.system_ext.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/test-keys
     with:  ro.system_ext.build.fingerprint=OnePlus/lineage_instantnoodlep/instantnoodlep:13/TQ3A.230901.001/2023100409:userdebug/release-keys
  replace:  ro.system_ext.build.tags=test-keys
     with:  ro.system_ext.build.tags=release-keys
    signing: SdkSandbox.apk                                             (build/make/target/product/security/sdk_sandbox)
    signing: AdServicesApk.apk                                          (packages/modules/AdServices/adservices/apk/com.android.adservices.api)
Traceback (most recent call last):
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/internal/stdlib/runpy.py", line 86, in _run_code
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/__main__.py", line 12, in <module>
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/internal/stdlib/runpy.py", line 86, in _run_code
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/sign_target_files_apks.py", line 1621, in <module>
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/sign_target_files_apks.py", line 1596, in main
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/sign_target_files_apks.py", line 566, in ProcessTargetFiles
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/sign_target_files_apks.py", line 477, in SignApk
  File "/nix/store/gd09vw1bphcvz6qkb373i3ff8ba416rp-ota-tools/bin/sign_target_files_apks/common.py", line 2395, in SignFile
common.ExternalError: Failed to run signapk.jar: return code 1:
java.io.FileNotFoundException: packages/modules/AdServices/adservices/apk/com.android.adservices.api.x509.pem (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.android.signapk.SignApk.readPublicKey(SignApk.java:194)
	at com.android.signapk.SignApk.main(SignApk.java:1185)

```

Looks like we need one more signing key, though I'm not sure where to add it and what it should be named.

**Comment by CyberShadow** [comment]
Got further with 33d5ef14e4813c1953873449a2fb638a0c338192.

**Comment by CyberShadow** [comment]
Duplicate of https://github.com/nix-community/robotnix/issues/221.
